# yaml-language-server: $schema=https://github.com/DavidAnson/markdownlint-cli2/raw/refs/heads/main/schema/markdownlint-cli2-config-schema.json
config:
  line-length:
    line_length: 120
  no-inline-html:
    allowed_elements:
      - br
