name = "Create: Beautiful Railways"
author = "KodiiTulip"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec1c6a550967e0535515e1da756c977254f505c89d6a60434ff457befc6c3c97"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
