name = "Create: Beautiful Railways"
author = "KodiiTulip"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e197872d874b3fff7017d26c88b0de5409695012cf44e27db2bf32144598b919"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
