name = "Create: Beautiful Railways"
author = "KodiiTulip"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3f96ede565596c32857d879bf161741266f2887447c630e95676862a432764d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
